name: instabid
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cross_file: ^0.3.4+2 # allows for getting the file path of the downloaded files
  cupertino_icons: ^1.0.8 # icon pack for Cupertino widgets
  dio: ^5.7.0 # HTTP client for making API calls
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.5.0 # form builder library which allows for easy creation of forms
  flutter_hooks: ^0.20.5 # hooks for Flutter
  flutter_secure_storage: ^9.2.2 # for storing sensitive data, such as API keys
  flutter_typeahead: ^5.2.0 # allows the user to search for items in a list
  form_builder_extra_fields: ^11.0.0 # additional fields for the form builder library
  form_builder_file_picker: ^4.2.0 # allows the user to pick a file for uploading
  form_builder_image_picker: ^4.1.0 # allows the user to pick an image for uploading
  form_builder_validators: ^11.0.0 # validators for the form builder library
  fpdart: ^1.1.0 # Used for error handling to avoid using try catch
  go_router: ^14.4.1 # routing for Flutter. also used for navigation and for the tabs
  go_router_builder: ^2.7.1 # builder for the go_router library
  hooks_riverpod: ^2.6.1 # hooks for Riverpod. for easier loading data from server. Recommend by riverpod
  material_design_icons_flutter: ^7.0.7296 # icon pack for Material Design widgets
  pretty_dio_logger: ^1.4.0 # logger for the dio HTTP client
  riverpod_annotation: ^2.6.1 # annotations for Riverpod
  window_manager: ^0.4.3 # allows for managing the app window.
  dart_mappable: ^4.3.0 # allows for mapping objects to JSON
  searchfield: ^1.1.7 # search field widget
  flutter_image_compress: ^2.3.0 # allows for compressing images
  image_picker: ^1.1.2 # allows the user to pick an image from their device
  path_provider: ^2.1.5 # allows for getting the path of the app's documents directory
  intl: ^0.19.0 # internationalization library. used for the time formats
  file_picker: ^8.1.3 # allows the user to pick a file for uploading
  cached_network_image: ^3.4.1
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  dart_mappable_builder: ^4.3.0  

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/src/core/assets/
  line_length: 80

scripts:
  pre-build: version update-pubspec

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
